
#数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/first?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    date-format: yyyy-MM-dd

# 设置thymeleaf模板的默认
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/views/

#  Ehcache缓存
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
    password:
    database: 1


#日志文件路径
logging:
  path: E:/logs/
  file: ${logging.path}vue_log



#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhg.studyelement.shiro.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

