
#数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/logistics?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    date-format: yyyy-MM-dd
#    view:
#      prefix: /view/
#      suffix: .html

# 取消thymeleaf模板的默认
  thymeleaf:
    cache: false
    enabled: false
#  Ehcache缓存
  cache:
    ehcache:
      config: classpath:ehcache.xml

#日志文件路径
logging:
  path: E:/logs/
  file: ${logging.path}vue_log

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhg.studyelement.pojo
