
#数据库数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      username: ENC(KW960Qq2tpleeLt1PlmINw==)
      password: ENC(RrEXaujhkwwXAKYp9apWdQ==)
      url: jdbc:mysql://localhost:3306/logistics?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    date-format: yyyy-MM-dd

# 设置thymeleaf模板的默认
  thymeleaf:
    cache: false
    enabled: true  # 默认true
    prefix: classpath:/views/
    suffix: .html

#  Ehcache缓存
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
    password:
    database: 1


#日志文件路径
logging:
  path: E:/logs/
  file: ${logging.path}vue_log

#数据库配置加密密钥
jasypt:
  encryptor:
    password: study

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhg.studyelement.shiro.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

# febs 配置
febs:
  # 是否在控制台打印 sql语句
  showsql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /login,/img/**,/vue/**,/axios/**,/element-ui/**,/saveVerify,/userList/**,/**/*.css,/**/*.js
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index.html
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
  # 验证码
  validateCode:
    # 宽度，默认 146px
    width: 146
    # 高度，默认 33px
    height: 42
    # 验证码字符个数，默认4个字符
    length: 4
