
# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
    servlet:
      context-path: /vue-element
    port: 8086

spring:
# 取消thymeleaf模板的默认
  thymeleaf:
    cache: false
    enabled: false

# 设置静态资源文件
  resources:
    static-locations: classpath:/views/,classpath:/static/
#  环境选择
  profiles:
    active: dev

#日志文件路径
logging:
  path: E:/logs/
  file: ${logging.path}vue_log

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhg.studyelement.pojo
