
# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
        uri-encoding: UTF-8
    servlet:
      context-path: /vue-element
    port: 8886

spring:
# 设置静态资源文件
  resources:
    static-locations: classpath:/views/,classpath:/static/
  profiles:
    active: dev

